[project]
name = "functions"
version = "0.1.0"
description = ""
authors = [
    {name = "devUtilityapp",email = "dev.utility.app@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "firebase-functions>=0.1.0,<0.2.0",
    "functions-framework>=3.0.0,<4.0.0",
    "yt-dlp>=2026.7.4,<2027.0.0",
    "firebase-admin>=6.3.0"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
