/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as YoutubeDownloaderImport } from './routes/youtube-downloader'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const YoutubeDownloaderRoute = YoutubeDownloaderImport.update({
  path: '/youtube-downloader',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/youtube-downloader': {
      id: '/youtube-downloader'
      path: '/youtube-downloader'
      fullPath: '/youtube-downloader'
      preLoaderRoute: typeof YoutubeDownloaderImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  YoutubeDownloaderRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/youtube-downloader"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/youtube-downloader": {
      "filePath": "youtube-downloader.ts"
    }
  }
}
ROUTE_MANIFEST_END */
